# Generated by Django 5.2.12 on 2026-04-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('running', 'Running'), ('upcoming', 'Upcoming')], default='complete', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='is_before',
            field=models.BooleanField(default=False, help_text='Check if this is a BEFORE image'),
        ),
    ]
