# Generated by Django 5.2.12 on 2026-04-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Use class like flaticon-bedroom', max_length=100),
        ),
    ]
