# Generated by Django 5.2.12 on 2026-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('pricing', 'Pricing'), ('design', 'Design Consultation'), ('complaint', 'Complaint')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
