# Generated by Django 5.2.12 on 2026-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_category_contact_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
