# Generated by Django 5.2.12 on 2026-05-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_qr',
            field=models.ImageField(blank=True, help_text='QR code image linking to the company Instagram profile', null=True, upload_to='site/qr/'),
        ),
    ]
